# Generated by Django 3.2.9 on 2023-02-11 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_feed_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='interval',
            field=models.PositiveSmallIntegerField(default=600, help_text='in sec', validators=[django.core.validators.MinValueValidator(60)]),
        ),
    ]
