version: "3.8"

services:
  app:
    build:
      context: .
      args:
        - DEBUG=${DEBUG}
    container_name: backend
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./src:/app
      - ./volumes/media:/media
      - ./volumes/static:/static
      - db:/db
    ports:
      - 8000:8000
    command: gunicorn --bind 0.0.0.0:8000 --timeout 600 --log-level debug --reload
      --workers 4 core.wsgi:application

volumes:
  db: