version: "3.8"

services:
  web:
    image: w0rng/rss-feed:latest
    volumes:
      - ./src:/app
      - static:/static
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput --clear &&
             gunicorn core.wsgi --workers 5 --bind 0.0.0.0:8000"
    restart: unless-stopped
    depends_on:
      - db

  scheduler:
    image: w0rng/rss-feed:latest
    command: [ "python", "manage.py", "update_feeds" ]
    restart: unless-stopped
    depends_on:
      - db
      - web

  db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  caddy:
    image: caddy:2.1.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/:/etc/caddy/
      - static:/static
    restart: unless-stopped
    depends_on:
      - web

volumes:
  postgres_data:
  static:
