version: "3.8"

services:
  app: &base-image
    build:
      context: .
      args:
        - DEBUG=${DEBUG}
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./src:/app
      - media:/media
      - static:/static
      - nltk:/root/nltk_data
      - db:/db
    container_name: backend
    ports:
      - 8000:8000
    command: gunicorn --bind 0.0.0.0:8000 --timeout 600 --log-level debug --reload
      --workers 4 core.wsgi:application
    depends_on:
      - redis

  dramatiq:
    <<: *base-image
    container_name: dramatiq
    command: python manage.py rundramatiq
    ports: []
    depends_on:
      - app
      - redis

  sheduler:
    <<: *base-image
    container_name: sheduler
    command: python manage.py run_scheduler
    ports: [ ]
    depends_on:
      - app
      - redis
      - dramatiq

  redis:
    image: redis:alpine
    container_name: redis


volumes:
  db:
  media:
  static:
  nltk: