version: "3.8"

services:
  web:
    image: w0rng/rss-feed:latest
    ports:
      - "80:8000"
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    restart: unless-stopped
    depends_on:
      - db

  scheduler:
    image: w0rng/rss-feed:latest
    command: [ "python", "manage.py", "update_feeds" ]
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  postgres_data:
