version: "3.8"

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./db:/app/db
    restart: unless-stopped

  scheduler:
    build: .
    command: [ "python","-u", "scheduler.py" ]
    volumes:
      - ./db:/app/db
    restart: unless-stopped
