version: "3.8"

services:
  db:
    image: postgres:13.10-alpine
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped

  app: &base-image
    build:
      context: .
      args:
        - DEBUG=${DEBUG}
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./src:/app
      - media:/media
      - static:/static
      - nltk:/root/nltk_data
    container_name: backend
    ports:
      - 8000:8000
    command: gunicorn --bind 0.0.0.0:8000 --timeout 600 --log-level debug --reload
      --workers 4 core.wsgi:application
    depends_on:
      - redis
      - db

  dramatiq:
    <<: *base-image
    container_name: dramatiq
    command: python manage.py rundramatiq -p 1 -t 2
    ports: []
    depends_on:
      - app
      - redis
      - db

  sheduler:
    <<: *base-image
    container_name: sheduler
    command: python manage.py run_scheduler
    ports: [ ]
    depends_on:
      - app
      - redis
      - dramatiq
      - db


volumes:
  db:
  media:
  static:
  nltk: