# Generated by Django 5.0 on 2023-12-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="title",
            field=models.TextField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.URLField(default=None, max_length=10240, null=True),
        ),
    ]
