# Generated by Django 5.0 on 2023-12-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="feed",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
